In [15]:
from sklearn.datasets import load_digits
from sklearn.ensemble import GradientBoostingClassifier
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

import numpy as np

In [2]:
data = load_digits()
X = data.data/255
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.3)

In [5]:
#model 1: Grid Search Gradient Boost
np.random.seed(6)
learning_rate = np.logspace(-3,3,10)
grid_para = dict(learning_rate = learning_rate)

cv_model = GridSearchCV(GradientBoostingClassifier(),grid_para)
cv_model.fit(X_train, y_train)

np.random.seed(6)
clf1 = GradientBoostingClassifier(learning_rate = cv_model.best_params_['learning_rate'])
clf1.fit(X_train, y_train)
y_predict = clf1.predict(X_test)


/anaconda3/envs/Tensorflow_test/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/anaconda3/envs/Tensorflow_test/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [56]:
print('test accuracy:', clf1.score(X_test, y_test))
print(confusion_matrix(y_test, y_predict))

test accuracy: 0.9685185185185186
[[52  0  0  0  0  0  0  0  0  0]
 [ 0 47  2  0  0  0  0  0  0  0]
 [ 0  1 55  0  0  0  0  0  0  0]
 [ 0  0  0 53  0  0  0  1  2  0]
 [ 0  0  0  0 49  0  0  1  0  0]
 [ 0  0  0  0  0 53  0  0  1  0]
 [ 0  0  0  0  0  1 64  0  1  0]
 [ 1  0  0  0  1  0  0 49  1  1]
 [ 0  1  0  0  0  0  0  0 43  0]
 [ 1  0  0  0  0  0  0  0  1 58]]


In [47]:
#model 2: XG boost
np.random.seed(6)
learning_rate = np.logspace(-2,2,4)
grid_para2 = dict(learning_rate = learning_rate)
clf2 = GridSearchCV(XGBClassifier(), grid_para2)
clf2.fit(X_train, y_train)
print(clf2.best_score_)
print(clf2.best_params_)

/anaconda3/envs/Tensorflow_test/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/anaconda3/envs/Tensorflow_test/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.9506762132060461
{'learning_rate': 0.21544346900318834}


In [54]:
clf2_2 = XGBClassifier(learing_rate = clf2.best_params_['learning_rate'], )
y_predict2 = clf2.predict(X_test)
print('test accuracy:',clf2.score(X_test, y_test))
print(confusion_matrix(y_test, y_predict2))

test accuracy: 0.9685185185185186
[[52  0  0  0  0  0  0  0  0  0]
 [ 0 47  2  0  0  0  0  0  0  0]
 [ 0  1 55  0  0  0  0  0  0  0]
 [ 0  0  0 53  0  0  0  1  2  0]
 [ 0  0  0  0 49  0  0  1  0  0]
 [ 0  0  0  0  0 52  0  0  1  1]
 [ 0  0  0  0  0  1 64  0  1  0]
 [ 1  0  0  0  0  0  0 51  0  1]
 [ 0  2  0  0  0  0  0  2 40  0]
 [ 0  0  0  0  0  0  0  0  0 60]]


In [55]:
# model3: Decision tree with ada boost
np.random.seed(6)
clf3 = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5))
clf3.fit(X_train, y_train)
print('test accuracy:', clf3.score(X_test, y_test))


test accuracy: 0.9425925925925925


In [35]:
# model4: decision tree with ada boost - grid search
np.random.seed(6)
learning_rate = np.logspace(-2,2,10)
n_estimator = np.arange(10,200,30)
grid_para = dict(learning_rate = learning_rate, n_estimators = n_estimator)
model = GridSearchCV(AdaBoostClassifier(DecisionTreeClassifier(max)),grid_para)
model.fit(X_train,y_train)
print(model.best_score_)
print(model.best_params_)

/anaconda3/envs/Tensorflow_test/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.8210023866348448
{'learning_rate': 1.6681005372000592, 'n_estimators': 160}


In [53]:
np.random.seed(6)
clf3 = AdaBoostClassifier(DecisionTreeClassifier(),learning_rate= model.best_params_['learning_rate'], n_estimators = model.best_params_['n_estimators'])
clf3.fit(X_train, y_train)
print('accuracy:', clf3.score(X_test, y_test))

accuracy: 0.8444444444444444


In [37]:
# model5: ada boost alone
np.random.seed(6)
clf3 = AdaBoostClassifier(learning_rate = 1.67, n_estimators = 160)
clf3.fit(X_train, y_train)
print('accuracy:',clf3.score(X_test, y_test))

accuracy: 0.6851851851851852
